version: "2"
run:
  tests: true
linters:
  enable:
    - asciicheck
    - bidichk
    - gocheckcompilerdirectives
    - misspell
    - rowserrcheck
    - sqlclosecheck
  disable:
    - gochecknoglobals
    - prealloc
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF1008"
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
